package com.academic.request;

import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Called by the Accounts service after a fee payment is recorded.
 * This module fires the FCM push notification to the student's devices.
 *
 * The Accounts service owns the payment logic & DB save;
 * this endpoint only handles the notification dispatch.
 */
@Data
public class FeePaymentNotificationRequest {

    // ── Who to notify ─────────────────────────────────────────────────────────

    /** Student's user ID (from the users table). Used to resolve FCM tokens. */
    @NotNull(message = "studentUserId is required")
    private Integer studentUserId;

    /** Student's name (for personalizing the notification message). */
    private String studentName;

    // ── Payment summary ───────────────────────────────────────────────────────

    /** Fee heads that were paid in this transaction (e.g. ["Tuition Fee", "Lab Fee"]). */
    private List<String> paidFeeHeads;

    /** Total amount paid in this transaction. */
    @NotNull(message = "amountPaid is required")
    private BigDecimal amountPaid;

    /** Remaining balance after this payment. */
    private BigDecimal remainingBalance;

    /** Bank / payment mode used (e.g. "SBI Bank", "Cash", "Online"). */
    private String paidVia;

    /** Receipt / transaction reference number generated by Accounts service. */
    private String receiptNumber;

    /** Date of payment. */
    private LocalDate paymentDate;

    // ── Optional deep-link data sent in FCM data payload ──────────────────────

    /**
     * Screen name the app should open when notification is tapped.
     * e.g. "FEE_RECEIPT"
     */
    private String deepLinkScreen;

    /**
     * Any extra key-value pairs to forward in the FCM data payload.
     * e.g. { "receiptId": "123" }
     */
    private java.util.Map<String, String> extraData;
}
